###
### Networks
###

networks:
  ingress:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge

###
### Include
###

include:
  - path: ./docker/apps.yml
  - path: ./docker/files.yml
  - path: ./docker/data.yml
  - path: ./docker/grammar.yml
  - path: ./docker/grist.yml
  - path: ./docker/home.yml
  - path: ./docker/meetings.yml
