services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: files_projectsend
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - files_config:/config
      - ${FILES_DATA_DIR}:/data
    ports:
      - ${FILES_PORT}:80
    restart: unless-stopped
    networks:
      - frontend

volumes:
  files_config:
